# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import test_pb2 as test__pb2


class pushServerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.somethingNew = channel.stream_stream(
        '/pushServer/somethingNew',
        request_serializer=test__pb2.req.SerializeToString,
        response_deserializer=test__pb2.res.FromString,
        )
    self.justHello = channel.unary_unary(
        '/pushServer/justHello',
        request_serializer=test__pb2.req.SerializeToString,
        response_deserializer=test__pb2.res.FromString,
        )


class pushServerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def somethingNew(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def justHello(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_pushServerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'somethingNew': grpc.stream_stream_rpc_method_handler(
          servicer.somethingNew,
          request_deserializer=test__pb2.req.FromString,
          response_serializer=test__pb2.res.SerializeToString,
      ),
      'justHello': grpc.unary_unary_rpc_method_handler(
          servicer.justHello,
          request_deserializer=test__pb2.req.FromString,
          response_serializer=test__pb2.res.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'pushServer', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
