# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='test.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\ntest.proto\"\x12\n\x03req\x12\x0b\n\x03\x66oo\x18\x01 \x01(\t\"\x1f\n\x03res\x12\x0b\n\x03\x62\x61r\x18\x01 \x01(\t\x12\x0b\n\x03key\x18\x02 \x01(\t2I\n\npushServer\x12 \n\x0csomethingNew\x12\x04.req\x1a\x04.res\"\x00(\x01\x30\x01\x12\x19\n\tjustHello\x12\x04.req\x1a\x04.res\"\x00\x62\x06proto3')
)




_REQ = _descriptor.Descriptor(
  name='req',
  full_name='req',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='foo', full_name='req.foo', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=32,
)


_RES = _descriptor.Descriptor(
  name='res',
  full_name='res',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bar', full_name='res.bar', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='key', full_name='res.key', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=65,
)

DESCRIPTOR.message_types_by_name['req'] = _REQ
DESCRIPTOR.message_types_by_name['res'] = _RES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

req = _reflection.GeneratedProtocolMessageType('req', (_message.Message,), dict(
  DESCRIPTOR = _REQ,
  __module__ = 'test_pb2'
  # @@protoc_insertion_point(class_scope:req)
  ))
_sym_db.RegisterMessage(req)

res = _reflection.GeneratedProtocolMessageType('res', (_message.Message,), dict(
  DESCRIPTOR = _RES,
  __module__ = 'test_pb2'
  # @@protoc_insertion_point(class_scope:res)
  ))
_sym_db.RegisterMessage(res)



_PUSHSERVER = _descriptor.ServiceDescriptor(
  name='pushServer',
  full_name='pushServer',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=67,
  serialized_end=140,
  methods=[
  _descriptor.MethodDescriptor(
    name='somethingNew',
    full_name='pushServer.somethingNew',
    index=0,
    containing_service=None,
    input_type=_REQ,
    output_type=_RES,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='justHello',
    full_name='pushServer.justHello',
    index=1,
    containing_service=None,
    input_type=_REQ,
    output_type=_RES,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PUSHSERVER)

DESCRIPTOR.services_by_name['pushServer'] = _PUSHSERVER

# @@protoc_insertion_point(module_scope)
