# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='test.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\ntest.proto\"\x1a\n\nclientInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x18\n\x08response\x12\x0c\n\x04info\x18\x01 \x01(\t25\n\npushServer\x12\'\n\tsubscribe\x12\x0b.clientInfo\x1a\t.response\"\x00\x30\x01\x62\x06proto3')
)




_CLIENTINFO = _descriptor.Descriptor(
  name='clientInfo',
  full_name='clientInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='clientInfo.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=40,
)


_RESPONSE = _descriptor.Descriptor(
  name='response',
  full_name='response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='info', full_name='response.info', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=66,
)

DESCRIPTOR.message_types_by_name['clientInfo'] = _CLIENTINFO
DESCRIPTOR.message_types_by_name['response'] = _RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

clientInfo = _reflection.GeneratedProtocolMessageType('clientInfo', (_message.Message,), dict(
  DESCRIPTOR = _CLIENTINFO,
  __module__ = 'test_pb2'
  # @@protoc_insertion_point(class_scope:clientInfo)
  ))
_sym_db.RegisterMessage(clientInfo)

response = _reflection.GeneratedProtocolMessageType('response', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSE,
  __module__ = 'test_pb2'
  # @@protoc_insertion_point(class_scope:response)
  ))
_sym_db.RegisterMessage(response)



_PUSHSERVER = _descriptor.ServiceDescriptor(
  name='pushServer',
  full_name='pushServer',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=68,
  serialized_end=121,
  methods=[
  _descriptor.MethodDescriptor(
    name='subscribe',
    full_name='pushServer.subscribe',
    index=0,
    containing_service=None,
    input_type=_CLIENTINFO,
    output_type=_RESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PUSHSERVER)

DESCRIPTOR.services_by_name['pushServer'] = _PUSHSERVER

# @@protoc_insertion_point(module_scope)
